logging.path: logs
spring:
    datasource:
       name: springbootservice
       url: jdbc:mysql://127.0.0.1:3306/hdsk-site
       username: root
       password: root
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name: com.mysql.jdbc.Driver
       filters:  stat
       maxActive:  20
       initialSize:  1
       maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

mybatis:
   mapper-locations: classpath:mapping/*.xml
   type-aliases-package: com.houdask.site.user.dao

#pagehelper分页
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

  #应用名
dubbo:
   application:
       name: user-service-provider
    #负责人
       owner: hdsk
    #注册zookeeper的地址
dubbo:
    registry:
       address: zookeeper://localhost:2181

    #扫包
dubbo:
    annotation:
       package: com.houdask.site.user
    #协议 (有 dubbo、rest、http、hessian、webservice)
dubbo:
   protocol:
      name: dubbo
    #协议暴露服务的端口(Integer类型)
      port: 20880
            #序列化方式(kryo是目前效率最高的)
      serialization: kryo
#序列化优化的实现类
      optimizer: com.houdask.site.common.config.SerializationOptimizerImpl
      #Dubbox的REST支持
dubbo:
   rest:
       name:  rest
       port:  8082
       server:  tomcat


