server:
    port: 8100
  #${random.int[9000,9999]}
adminPath: /V1
## Dubbo 服务消费者配置
spring:
  dubbo:
     scan: com.houdask.site
     application:
        name: consumer-web
          #负责人
      #注册zookeeper的地址
     registry:
        address: zookeeper://localhost:2181

  mvc:
    view:
    # 页面默认前缀目录
      prefix: /WEB-INF/jsp/
      # 响应页面默认后缀
      suffix: .jsp
logging:
  path:  logs/web
  config: classpath:web-logback.xml
#logging.config=classpath:pm-logback.xml
#logging.path=log








